// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dft1_HH_
#define _dft1_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "top_faddfsub_32nsdEe.h"
#include "top_fadd_32ns_32neOg.h"
#include "top_fmul_32ns_32nfYi.h"
#include "dft1_cos_coefficibkb.h"
#include "dft1_sin_coefficicud.h"

namespace ap_rtl {

struct dft1 : public sc_module {
    // Port declarations 23
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<8> > real_sample_address0;
    sc_out< sc_logic > real_sample_ce0;
    sc_in< sc_lv<32> > real_sample_q0;
    sc_out< sc_lv<8> > imag_sample_address0;
    sc_out< sc_logic > imag_sample_ce0;
    sc_in< sc_lv<32> > imag_sample_q0;
    sc_out< sc_lv<8> > dft_real_address0;
    sc_out< sc_logic > dft_real_ce0;
    sc_out< sc_logic > dft_real_we0;
    sc_out< sc_lv<32> > dft_real_d0;
    sc_in< sc_lv<32> > dft_real_q0;
    sc_out< sc_lv<8> > dft_imag_address0;
    sc_out< sc_logic > dft_imag_ce0;
    sc_out< sc_logic > dft_imag_we0;
    sc_out< sc_lv<32> > dft_imag_d0;
    sc_in< sc_lv<32> > dft_imag_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    dft1(sc_module_name name);
    SC_HAS_PROCESS(dft1);

    ~dft1();

    sc_trace_file* mVcdFile;

    dft1_cos_coefficibkb* cos_coefficients_tab_1_U;
    dft1_sin_coefficicud* sin_coefficients_tab_1_U;
    top_faddfsub_32nsdEe<1,5,32,32,32>* top_faddfsub_32nsdEe_U0;
    top_fadd_32ns_32neOg<1,5,32,32,32>* top_fadd_32ns_32neOg_U1;
    top_fmul_32ns_32nfYi<1,4,32,32,32>* top_fmul_32ns_32nfYi_U2;
    top_fmul_32ns_32nfYi<1,4,32,32,32>* top_fmul_32ns_32nfYi_U3;
    top_fmul_32ns_32nfYi<1,4,32,32,32>* top_fmul_32ns_32nfYi_U4;
    top_fmul_32ns_32nfYi<1,4,32,32,32>* top_fmul_32ns_32nfYi_U5;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<19> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > cos_coefficients_tab_1_address0;
    sc_signal< sc_logic > cos_coefficients_tab_1_ce0;
    sc_signal< sc_lv<32> > cos_coefficients_tab_1_q0;
    sc_signal< sc_lv<8> > sin_coefficients_tab_1_address0;
    sc_signal< sc_logic > sin_coefficients_tab_1_ce0;
    sc_signal< sc_lv<32> > sin_coefficients_tab_1_q0;
    sc_signal< sc_lv<32> > grp_fu_133_p2;
    sc_signal< sc_lv<32> > reg_157;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_lv<32> > grp_fu_137_p2;
    sc_signal< sc_lv<32> > reg_163;
    sc_signal< sc_lv<8> > n_2_fu_181_p2;
    sc_signal< sc_lv<8> > n_2_reg_224;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<8> > real_sample_addr_reg_229;
    sc_signal< sc_lv<1> > exitcond1_fu_175_p2;
    sc_signal< sc_lv<8> > imag_sample_addr_reg_234;
    sc_signal< sc_lv<9> > w_3_fu_203_p2;
    sc_signal< sc_lv<9> > w_3_reg_242;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_fu_197_p2;
    sc_signal< sc_lv<8> > dft_real_addr_reg_257;
    sc_signal< sc_lv<8> > dft_imag_addr_reg_262;
    sc_signal< sc_lv<32> > cos_coefficients_tab_3_reg_267;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > real_sample_load_reg_273;
    sc_signal< sc_lv<32> > sin_coefficients_tab_3_reg_279;
    sc_signal< sc_lv<32> > imag_sample_load_reg_285;
    sc_signal< sc_lv<32> > grp_fu_141_p2;
    sc_signal< sc_lv<32> > tmp_s_reg_291;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > grp_fu_145_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_296;
    sc_signal< sc_lv<32> > grp_fu_149_p2;
    sc_signal< sc_lv<32> > tmp_4_reg_301;
    sc_signal< sc_lv<32> > grp_fu_153_p2;
    sc_signal< sc_lv<32> > tmp_5_reg_306;
    sc_signal< sc_lv<32> > dft_real_load_reg_311;
    sc_signal< sc_lv<32> > dft_imag_load_reg_316;
    sc_signal< sc_lv<8> > n_reg_110;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<9> > w_reg_122;
    sc_signal< sc_logic > ap_CS_fsm_state19;
    sc_signal< sc_lv<32> > n_cast_fu_169_p1;
    sc_signal< sc_lv<32> > ind_cast_fu_215_p1;
    sc_signal< sc_lv<32> > w_cast2_fu_187_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<32> > grp_fu_133_p0;
    sc_signal< sc_lv<32> > grp_fu_133_p1;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<32> > grp_fu_137_p0;
    sc_signal< sc_lv<32> > grp_fu_137_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<8> > tmp_fu_193_p1;
    sc_signal< sc_lv<8> > ind_fu_209_p2;
    sc_signal< sc_lv<2> > grp_fu_133_opcode;
    sc_signal< sc_lv<19> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<19> ap_ST_fsm_state1;
    static const sc_lv<19> ap_ST_fsm_state2;
    static const sc_lv<19> ap_ST_fsm_state3;
    static const sc_lv<19> ap_ST_fsm_state4;
    static const sc_lv<19> ap_ST_fsm_state5;
    static const sc_lv<19> ap_ST_fsm_state6;
    static const sc_lv<19> ap_ST_fsm_state7;
    static const sc_lv<19> ap_ST_fsm_state8;
    static const sc_lv<19> ap_ST_fsm_state9;
    static const sc_lv<19> ap_ST_fsm_state10;
    static const sc_lv<19> ap_ST_fsm_state11;
    static const sc_lv<19> ap_ST_fsm_state12;
    static const sc_lv<19> ap_ST_fsm_state13;
    static const sc_lv<19> ap_ST_fsm_state14;
    static const sc_lv<19> ap_ST_fsm_state15;
    static const sc_lv<19> ap_ST_fsm_state16;
    static const sc_lv<19> ap_ST_fsm_state17;
    static const sc_lv<19> ap_ST_fsm_state18;
    static const sc_lv<19> ap_ST_fsm_state19;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<8> ap_const_lv8_80;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<9> ap_const_lv9_100;
    static const sc_lv<9> ap_const_lv9_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_cos_coefficients_tab_1_address0();
    void thread_cos_coefficients_tab_1_ce0();
    void thread_dft_imag_address0();
    void thread_dft_imag_ce0();
    void thread_dft_imag_d0();
    void thread_dft_imag_we0();
    void thread_dft_real_address0();
    void thread_dft_real_ce0();
    void thread_dft_real_d0();
    void thread_dft_real_we0();
    void thread_exitcond1_fu_175_p2();
    void thread_exitcond_fu_197_p2();
    void thread_grp_fu_133_opcode();
    void thread_grp_fu_133_p0();
    void thread_grp_fu_133_p1();
    void thread_grp_fu_137_p0();
    void thread_grp_fu_137_p1();
    void thread_imag_sample_address0();
    void thread_imag_sample_ce0();
    void thread_ind_cast_fu_215_p1();
    void thread_ind_fu_209_p2();
    void thread_n_2_fu_181_p2();
    void thread_n_cast_fu_169_p1();
    void thread_real_sample_address0();
    void thread_real_sample_ce0();
    void thread_sin_coefficients_tab_1_address0();
    void thread_sin_coefficients_tab_1_ce0();
    void thread_tmp_fu_193_p1();
    void thread_w_3_fu_203_p2();
    void thread_w_cast2_fu_187_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
