// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dft3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dft3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dft3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dft3::ap_ST_fsm_state1 = "1";
const sc_lv<3> dft3::ap_ST_fsm_state2 = "10";
const sc_lv<3> dft3::ap_ST_fsm_state3 = "100";
const sc_lv<32> dft3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dft3::ap_const_lv32_1 = "1";
const sc_lv<32> dft3::ap_const_lv32_2 = "10";
const sc_lv<9> dft3::ap_const_lv9_0 = "000000000";
const sc_lv<9> dft3::ap_const_lv9_100 = "100000000";
const sc_lv<9> dft3::ap_const_lv9_1 = "1";
const sc_lv<1> dft3::ap_const_lv1_1 = "1";
const bool dft3::ap_const_boolean_1 = true;

dft3::dft3(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_91_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_91_p2 );

    SC_METHOD(thread_dft_imag_address0);
    sensitive << ( w_cast_reg_103 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_imag_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_imag_d0);
    sensitive << ( imag_sample_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_imag_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_real_address0);
    sensitive << ( w_cast_reg_103 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_real_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_real_d0);
    sensitive << ( real_sample_q0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_dft_real_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_exitcond_fu_91_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( w_reg_74 );

    SC_METHOD(thread_imag_sample_address0);
    sensitive << ( w_cast_fu_85_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_imag_sample_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_real_sample_address0);
    sensitive << ( w_cast_fu_85_p1 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_real_sample_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_w_1_fu_97_p2);
    sensitive << ( w_reg_74 );

    SC_METHOD(thread_w_cast_fu_85_p1);
    sensitive << ( w_reg_74 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_91_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dft3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, real_sample_address0, "(port)real_sample_address0");
    sc_trace(mVcdFile, real_sample_ce0, "(port)real_sample_ce0");
    sc_trace(mVcdFile, real_sample_q0, "(port)real_sample_q0");
    sc_trace(mVcdFile, imag_sample_address0, "(port)imag_sample_address0");
    sc_trace(mVcdFile, imag_sample_ce0, "(port)imag_sample_ce0");
    sc_trace(mVcdFile, imag_sample_q0, "(port)imag_sample_q0");
    sc_trace(mVcdFile, dft_real_address0, "(port)dft_real_address0");
    sc_trace(mVcdFile, dft_real_ce0, "(port)dft_real_ce0");
    sc_trace(mVcdFile, dft_real_we0, "(port)dft_real_we0");
    sc_trace(mVcdFile, dft_real_d0, "(port)dft_real_d0");
    sc_trace(mVcdFile, dft_imag_address0, "(port)dft_imag_address0");
    sc_trace(mVcdFile, dft_imag_ce0, "(port)dft_imag_ce0");
    sc_trace(mVcdFile, dft_imag_we0, "(port)dft_imag_we0");
    sc_trace(mVcdFile, dft_imag_d0, "(port)dft_imag_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w_cast_fu_85_p1, "w_cast_fu_85_p1");
    sc_trace(mVcdFile, w_cast_reg_103, "w_cast_reg_103");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, w_1_fu_97_p2, "w_1_fu_97_p2");
    sc_trace(mVcdFile, w_1_reg_112, "w_1_reg_112");
    sc_trace(mVcdFile, exitcond_fu_91_p2, "exitcond_fu_91_p2");
    sc_trace(mVcdFile, w_reg_74, "w_reg_74");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dft3::~dft3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dft3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond_fu_91_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        w_reg_74 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        w_reg_74 = w_1_reg_112.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        w_1_reg_112 = w_1_fu_97_p2.read();
        w_cast_reg_103 = w_cast_fu_85_p1.read();
    }
}

void dft3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dft3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dft3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dft3::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void dft3::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_91_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void dft3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dft3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_91_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dft3::thread_dft_imag_address0() {
    dft_imag_address0 =  (sc_lv<8>) (w_cast_reg_103.read());
}

void dft3::thread_dft_imag_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        dft_imag_ce0 = ap_const_logic_1;
    } else {
        dft_imag_ce0 = ap_const_logic_0;
    }
}

void dft3::thread_dft_imag_d0() {
    dft_imag_d0 = imag_sample_q0.read();
}

void dft3::thread_dft_imag_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        dft_imag_we0 = ap_const_logic_1;
    } else {
        dft_imag_we0 = ap_const_logic_0;
    }
}

void dft3::thread_dft_real_address0() {
    dft_real_address0 =  (sc_lv<8>) (w_cast_reg_103.read());
}

void dft3::thread_dft_real_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        dft_real_ce0 = ap_const_logic_1;
    } else {
        dft_real_ce0 = ap_const_logic_0;
    }
}

void dft3::thread_dft_real_d0() {
    dft_real_d0 = real_sample_q0.read();
}

void dft3::thread_dft_real_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        dft_real_we0 = ap_const_logic_1;
    } else {
        dft_real_we0 = ap_const_logic_0;
    }
}

void dft3::thread_exitcond_fu_91_p2() {
    exitcond_fu_91_p2 = (!w_reg_74.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(w_reg_74.read() == ap_const_lv9_100);
}

void dft3::thread_imag_sample_address0() {
    imag_sample_address0 =  (sc_lv<8>) (w_cast_fu_85_p1.read());
}

void dft3::thread_imag_sample_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        imag_sample_ce0 = ap_const_logic_1;
    } else {
        imag_sample_ce0 = ap_const_logic_0;
    }
}

void dft3::thread_real_sample_address0() {
    real_sample_address0 =  (sc_lv<8>) (w_cast_fu_85_p1.read());
}

void dft3::thread_real_sample_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        real_sample_ce0 = ap_const_logic_1;
    } else {
        real_sample_ce0 = ap_const_logic_0;
    }
}

void dft3::thread_w_1_fu_97_p2() {
    w_1_fu_97_p2 = (!w_reg_74.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(w_reg_74.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft3::thread_w_cast_fu_85_p1() {
    w_cast_fu_85_p1 = esl_zext<32,9>(w_reg_74.read());
}

void dft3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_91_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

